import turtle
t=turtle.Turtle()
t.width(2)
t.penup()
t.goto(-150,-50)
t.pendown()
for i in range(2):
  t.forward(300)
  t.left(90)
  t.forward(150)
  t.left(90)
t.penup()
t.goto(-45,-40)
t.pendown()
for i in range(5):
  t.forward(90)
  t.left(72)
t.penup()
t.goto(-4,-13)
t.pendown()
t.circle(40)
t.penup()
t.goto(-16,16)
t.pendown()
t.write("AJ",font=("Arial",12))
t.hideturtle()
input()